version: '3.8'
services:
  scraper:
    build: ./
    ports:
      - 3002-3002
    environment:
      DB_URI: mongodb://db/steam-games
  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - scraper:/data/db
volumes:
  scraper:
